In [1]:
from __future__ import print_function
import torch

In [2]:
#Tensors 类似于 NumPy 的 ndarrays ，同时 Tensors 可以使用 GPU 进行计算。
#构造一个5x3矩阵，不初始化, torch.empty生成指定维数的空矩阵，但是浮点的零仅仅是接近真正的零而已
x = torch.empty(5, 3)
print(x)

tensor([[6.6284e-10, 1.0471e-11, 2.6512e-09],
        [1.0431e-08, 6.7367e-10, 6.3078e-10],
        [1.6504e-07, 1.6765e+22, 4.0335e-11],
        [4.2330e+21, 1.6534e+19, 3.0478e+32],
        [2.5704e+38, 4.5780e-41, 0.0000e+00]])


In [31]:
#构造5*3的矩阵，随机初始化，值是[0,1]之间的均匀分布，torch.rand(*sizes, out=None) → Tensor  out是结果张量
x1 = torch.rand(5, 3)
print('均匀分布 x3:', x1)
torch.rand(5, 3, out=x2)
print(x2)

#其它方式
#torch.randn(*sizes, out=None) → Tensor   标准正态分布，均值0方差为1
x3 = torch.randn(5,3)
print('标准正态分布 x3:', x3)

#全是零值, 且数据类型是long, 还可以是torch.float16 或者float32 float64 double，double似乎就是float64
x4 = torch.zeros(3, 3, dtype=torch.long)
print('零值 x4:', x4)

#线性间距向量，返回[start, end]之间包括左右两端点的均匀的steps个点
x5 = torch.linspace(3, 10, steps=5) # 返回[ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000]
print('线性间距向量 x5:', x5) 

#torch.normal(means, std, out=None) → → Tensor  离散正态分布
x = torch.arange(1, 6)
print(x)  # 返回Tensor，值是[1, 2, 3, 4, 5]，如果是torch.arange(1, 6, 2)返回[1,3,5]
print(type(x))
#这块有错误，是不是1.2.0版本改了接口？#
x4 = torch.normal(mean=torch.arange(1, 6), std=torch.arange(1, 6), dtype=torch.long)
print('离散正态分布，x4:', x4)

均匀分布 x3: tensor([[0.2769, 0.9593, 0.2887],
        [0.2878, 0.7441, 0.4703],
        [0.6810, 0.4147, 0.3314],
        [0.1262, 0.9629, 0.2363],
        [0.0380, 0.7453, 0.2864]])
tensor([[0.3104, 0.2282, 0.6397],
        [0.7013, 0.8593, 0.9675],
        [0.2672, 0.7682, 0.1052],
        [0.9259, 0.9995, 0.9305],
        [0.6098, 0.2131, 0.6972]])
标准正态分布 x3: tensor([[ 0.5366,  0.5383, -1.1500],
        [ 0.7291, -0.6663, -0.6069],
        [-1.1433, -0.6153,  0.0955],
        [ 0.4989, -0.3611, -0.6227],
        [-0.0511, -1.1925,  0.9378]])
零值 x4: tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
线性间距向量 x5: tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>


TypeError: normal() received an invalid combination of arguments - got (std=Tensor, dtype=torch.dtype, mean=Tensor, ), but expected one of:
 * (Tensor mean, Tensor std, torch.Generator generator, Tensor out)
 * (Tensor mean, float std, torch.Generator generator, Tensor out)
 * (float mean, Tensor std, torch.Generator generator, Tensor out)
 * (float mean, float std, tuple of ints size, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [41]:
#直接使用数据构造tensor
x = torch.tensor([5.5, 3])
print(x)

#创建一个tensor基于已经存在的tensor
#不过下面这行没看出新创建和已存在的有毛关系，除了在原x上调用new_ones
x = x.new_ones(1, 2, dtype=torch.double) # new_* methods take in sizes    
print(x)

# override dtype!   这里randn_like的第一个参数x作为size，相当于使用了x的size作为参数
x = torch.randn_like(x, dtype=torch.float)    
print(x)   # result has the same size                                   

#返回维度信息，返回的Size是一个元组
print(x.size()) #返回torch.Size([1, 2]) 

tensor([5.5000, 3.0000])
tensor([[1., 1.]], dtype=torch.float64)
tensor([[0.3607, 0.4669]])
torch.Size([1, 2])


In [52]:
#tensor的加法
x = torch.rand(2,3)
y = torch.rand(2,3)
print('x:', x)
print('y:', y)
print('x+y:', x+y)
print('x+y:', torch.add(x, y))  #相当于x+y

result = torch.empty(x.size())
torch.add(x, y, out=result) #结果返回给result变量
print(result)

#tenson的in-place加法
# adds x to y
y.add_(x)  #WTF! add_ 和 add 竟然都ok，有点坑人啊
y.add(x)
print('x:',x)
print('y:',y)
#print(y.add)
#print(y.add_)

#返回tensor某个维度数据
print('x:', x)
print(x[:,1]) #第二列
print(x[0,:]) #第一行

x: tensor([[0.8106, 0.4636, 0.0923],
        [0.3219, 0.4201, 0.5049]])
y: tensor([[0.3089, 0.9511, 0.5752],
        [0.7489, 0.0916, 0.2405]])
x+y: tensor([[1.1195, 1.4147, 0.6676],
        [1.0707, 0.5117, 0.7454]])
x+y: tensor([[1.1195, 1.4147, 0.6676],
        [1.0707, 0.5117, 0.7454]])
tensor([[1.1195, 1.4147, 0.6676],
        [1.0707, 0.5117, 0.7454]])
x: tensor([[0.8106, 0.4636, 0.0923],
        [0.3219, 0.4201, 0.5049]])
y: tensor([[1.1195, 1.4147, 0.6676],
        [1.0707, 0.5117, 0.7454]])
x: tensor([[0.8106, 0.4636, 0.0923],
        [0.3219, 0.4201, 0.5049]])
tensor([0.4636, 0.4201])
tensor([0.8106, 0.4636, 0.0923])


In [53]:
#tensor改变大小，如果你想改变一个 tensor 的大小或者形状，你可以使用 torch.view:
x = torch.randn(4, 4)
y = x.view(16)
# the size -1 is inferred from other dimensions。
z = x.view(-1, 8)  #-1就是说此维度根据其他维度而定，这里16个元素，第二个参数是8，所以推断第一个参数应该是2
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [56]:
#获取值
#如果你有一个元素 tensor ，使用 .item() 来获得这个 value 。
x = torch.randn(1)
print(x)
print(x.item()) #这个返回的是值
print(x[0]) #这个返回的还是一个tensor，为tensor(-0.0228)这样的

print(y)
print(y[0]) #返回y的第一个元素，因为y的size是[16]，即16个元素的一维向量

tensor([-0.0228])
-0.022770728915929794
tensor(-0.0228)
tensor([-1.1385, -0.3825, -0.8426,  0.8173, -0.4972, -0.3800, -1.5992, -1.4097,
         0.5380, -1.1813,  0.6219, -0.2905,  0.6948, -0.6373,  1.6898, -2.5792])
tensor(-1.1385)
